"""research_store — pure immutable research data storage core.

This package never imports ``vnpy`` or provider SDKs and never mutates
``~/.vntrader``. See INTERFACES.md for the binding contract.
"""

from .models import (
    Adjustment,
    AssetClass,
    AssetRef,
    BatchRecovery,
    BatchState,
    Completeness,
    ConflictError,
    ConflictPolicy,
    ConflictRecord,
    ConflictResolution,
    CoverageGapError,
    HeadConflictError,
    ImportReceipt,
    ImportRequest,
    IntegrityError,
    Interval,
    KnownGap,
    MissingFieldDataError,
    OriginMethod,
    PartitionReceipt,
    PendingCapabilityError,
    ReadOnlyError,
    RecordKind,
    RecoveryReport,
    RevisionReceipt,
    SealReceipt,
    SealRequest,
    Selection,
    SemanticSpec,
    SessionRecoveryReport,
    SnapshotRef,
    SnapshotRequest,
    StoreError,
    StoreExistsError,
    StoreNotFoundError,
    TimeLabel,
    UnavailableFieldError,
    UnknownDatasetError,
    UnresolvedConflictError,
    UnsupportedCapabilityError,
    compute_dataset_id,
    default_idempotency_key,
)
from .reader import SnapshotReader
from .aggregation import AggregatedBar, AggregatedSession, aggregate_session
from .session_recovery import SessionRecoveryError
from .retention import RetentionDecision, apply_retention, evaluate_retention
from .revisions import (
    import_asset,
    recover,
    recover_session,
    register_asset,
    resolve_conflict,
    seal,
)
from .sealing import SealError, SealPlan, plan_seal
from .schemas import BARS_SCHEMA_V1, SCHEMA_VERSION, TICKS_SCHEMA_V1, schema_for
from .snapshots import freeze, open_snapshot
from .store import Store, init_store, open_store

__version__ = "0.1.0.dev1"

__all__ = [
    "Adjustment",
    "AggregatedBar",
    "AggregatedSession",
    "AssetClass",
    "AssetRef",
    "BARS_SCHEMA_V1",
    "BatchRecovery",
    "BatchState",
    "Completeness",
    "ConflictError",
    "ConflictPolicy",
    "ConflictRecord",
    "ConflictResolution",
    "CoverageGapError",
    "HeadConflictError",
    "ImportReceipt",
    "ImportRequest",
    "IntegrityError",
    "Interval",
    "KnownGap",
    "MissingFieldDataError",
    "OriginMethod",
    "PartitionReceipt",
    "PendingCapabilityError",
    "ReadOnlyError",
    "RecordKind",
    "RecoveryReport",
    "RetentionDecision",
    "RevisionReceipt",
    "SCHEMA_VERSION",
    "SealError",
    "SealPlan",
    "SealReceipt",
    "SealRequest",
    "Selection",
    "SemanticSpec",
    "SessionRecoveryError",
    "SessionRecoveryReport",
    "SnapshotReader",
    "SnapshotRef",
    "SnapshotRequest",
    "Store",
    "StoreError",
    "StoreExistsError",
    "StoreNotFoundError",
    "TICKS_SCHEMA_V1",
    "TimeLabel",
    "UnavailableFieldError",
    "UnknownDatasetError",
    "UnresolvedConflictError",
    "UnsupportedCapabilityError",
    "__version__",
    "aggregate_session",
    "apply_retention",
    "compute_dataset_id",
    "default_idempotency_key",
    "evaluate_retention",
    "freeze",
    "import_asset",
    "init_store",
    "open_snapshot",
    "open_store",
    "plan_seal",
    "recover",
    "recover_session",
    "register_asset",
    "resolve_conflict",
    "schema_for",
    "seal",
]
